/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package HangmanPAT;

import com.sun.media.sound.DLSModulator;
import javax.swing.JOptionPane;

/**
 *
 * @author Morgan
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
       
       initComponents();
        printStackTrace();
       String words[]= new String[100];
        words[0]="skeleton";
        words[1]="backbone";
        words[2]="ball and socket joint";
        words[3]="bone";
        words[4]="breastbone";
        words[5]="cheekbone";
        words[6]="bone marrow";
        words[7]="clavicle";
        words[8]="coccyx";
        words[9]="collarbone";
        words[10]="endoskeleton";
        words[11]="femur";
        words[12]="fibula";
        words[13]="funny bone";
        words[14]="hinge joint";
        words[15]="hip";
        words[16]="hip bone";
        words[17]="humerus";
        words[18]="jawbone";
        words[19]="joint";
        words[20]="kneecap";
        words[21]="marrow";
        words[22]="metatarsal";
        words[23]="out";
        words[24]="patella"; 
        words[25]="pelvis";
        words[26]="pivot joint";
        words[27]="radius";
        words[28]="rib";
        words[29]="rib cage";
        words[30]="rotating joint";
        words[31]="scapula";
        words[32]="set";
        words[33]="shinbone";
        words[34]="shoulder bone";
        words[35]="sinus";
        words[36]="skull";
        words[37]="socket";
        words[38]="solar plexus";
        words[39]="spinal column";
        words[40]="spine";
        words[41]="sternum";
        words[42]="synovial fluid";
        words[43]="tailbone";
        words[44]="tarsus";
        words[45]="thigh bone";
        words[46]="tibia"; 
        words[47]="ulna";
        words[48]="vertebra";
        words[49]="vertebral column";
        words[50]="serotonin";
       words[51] = "food";                 
       
                
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jToolBar1 = new javax.swing.JToolBar();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        C_BTN = new javax.swing.JToggleButton();
        B_btn = new javax.swing.JToggleButton();
        D_BTN = new javax.swing.JToggleButton();
        E_BTN = new javax.swing.JToggleButton();
        F_BTN = new javax.swing.JToggleButton();
        G_BTN = new javax.swing.JToggleButton();
        H_BTN = new javax.swing.JToggleButton();
        I_BTN = new javax.swing.JToggleButton();
        J_BTN = new javax.swing.JToggleButton();
        K_BTN = new javax.swing.JToggleButton();
        L_BTN = new javax.swing.JToggleButton();
        N_BTN = new javax.swing.JToggleButton();
        M_BTN = new javax.swing.JToggleButton();
        O_BTN = new javax.swing.JToggleButton();
        U_BTN = new javax.swing.JToggleButton();
        Q_BTN = new javax.swing.JToggleButton();
        P_BTN = new javax.swing.JToggleButton();
        T_btn = new javax.swing.JToggleButton();
        Z_BTN = new javax.swing.JToggleButton();
        R_BTN = new javax.swing.JToggleButton();
        S_BTN = new javax.swing.JToggleButton();
        V_BTN = new javax.swing.JToggleButton();
        Y_BTN = new javax.swing.JToggleButton();
        X_BTN = new javax.swing.JToggleButton();
        W_BTN = new javax.swing.JToggleButton();
        restart_btn = new javax.swing.JButton();
        hints_btn = new javax.swing.JButton();
        A_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Logout_menu = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenuItem();
        Exit_menu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        help_menu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        C_BTN.setText("C");
        C_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_BTNActionPerformed(evt);
            }
        });

        B_btn.setText("B");
        B_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_btnActionPerformed(evt);
            }
        });

        D_BTN.setText("D");
        D_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_BTNActionPerformed(evt);
            }
        });

        E_BTN.setText("E");
        E_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_BTNActionPerformed(evt);
            }
        });

        F_BTN.setText("F");
        F_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_BTNActionPerformed(evt);
            }
        });

        G_BTN.setText("G");
        G_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_BTNActionPerformed(evt);
            }
        });

        H_BTN.setText("H");
        H_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_BTNActionPerformed(evt);
            }
        });

        I_BTN.setText("I");
        I_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_BTNActionPerformed(evt);
            }
        });

        J_BTN.setText("J");
        J_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_BTNActionPerformed(evt);
            }
        });

        K_BTN.setText("K");
        K_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_BTNActionPerformed(evt);
            }
        });

        L_BTN.setText("L");
        L_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_BTNActionPerformed(evt);
            }
        });

        N_BTN.setText("N");
        N_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_BTNActionPerformed(evt);
            }
        });

        M_BTN.setText("M");
        M_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_BTNActionPerformed(evt);
            }
        });

        O_BTN.setText("O");
        O_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_BTNActionPerformed(evt);
            }
        });

        U_BTN.setText("U");
        U_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_BTNActionPerformed(evt);
            }
        });

        Q_BTN.setText("Q");
        Q_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q_BTNActionPerformed(evt);
            }
        });

        P_BTN.setText("P");
        P_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_BTNActionPerformed(evt);
            }
        });

        T_btn.setText("T");
        T_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_btnActionPerformed(evt);
            }
        });

        Z_BTN.setText("Z");
        Z_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z_BTNActionPerformed(evt);
            }
        });

        R_BTN.setText("R");
        R_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_BTNActionPerformed(evt);
            }
        });

        S_BTN.setText("S");
        S_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_BTNActionPerformed(evt);
            }
        });

        V_BTN.setText("V");
        V_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_BTNActionPerformed(evt);
            }
        });

        Y_BTN.setText("Y");
        Y_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y_BTNActionPerformed(evt);
            }
        });

        X_BTN.setText("X");
        X_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X_BTNActionPerformed(evt);
            }
        });

        W_BTN.setText("W");
        W_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W_BTNActionPerformed(evt);
            }
        });

        restart_btn.setText("Restart");
        restart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart_btnActionPerformed(evt);
            }
        });

        hints_btn.setText("HINTS");

        A_btn.setText("A");
        A_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnActionPerformed(evt);
            }
        });

        Logout_menu.setText("File");

        logoutMenu.setText("logout");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        Logout_menu.add(logoutMenu);

        Exit_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Exit_menu.setText("exit");
        Exit_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_menuActionPerformed(evt);
            }
        });
        Logout_menu.add(Exit_menu);

        jMenuBar1.add(Logout_menu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        help_menu.setText("help");

        jMenuItem3.setText("game help");
        help_menu.add(jMenuItem3);

        jMenuBar1.add(help_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hints_btn)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Y_BTN)
                                    .addGap(18, 18, 18)
                                    .addComponent(Z_BTN)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restart_btn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(M_BTN)
                            .addGap(18, 18, 18)
                            .addComponent(N_BTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(O_BTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(P_BTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Q_BTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(R_BTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(S_BTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(T_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(U_BTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(V_BTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(W_BTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(X_BTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A_btn)
                        .addGap(31, 31, 31)
                        .addComponent(B_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(F_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(G_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(I_BTN)
                        .addGap(2, 2, 2)
                        .addComponent(J_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(K_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L_BTN)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_btn)
                    .addComponent(C_BTN)
                    .addComponent(D_BTN)
                    .addComponent(E_BTN)
                    .addComponent(F_BTN)
                    .addComponent(G_BTN)
                    .addComponent(H_BTN)
                    .addComponent(I_BTN)
                    .addComponent(K_BTN)
                    .addComponent(L_BTN)
                    .addComponent(J_BTN)
                    .addComponent(A_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_BTN)
                    .addComponent(N_BTN)
                    .addComponent(O_BTN)
                    .addComponent(P_BTN)
                    .addComponent(Q_BTN)
                    .addComponent(R_BTN)
                    .addComponent(S_BTN)
                    .addComponent(T_btn)
                    .addComponent(U_BTN)
                    .addComponent(V_BTN)
                    .addComponent(W_BTN)
                    .addComponent(X_BTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Y_BTN)
                    .addComponent(Z_BTN))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hints_btn)
                    .addComponent(restart_btn))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_menuActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_Exit_menuActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginScreen().setVisible(true);
            }
        });
        try {
            String sql= "Insert into player(playerID,name,surname,grade,score)  values(?,?,?,?,?)";
           
                  
        
        
        } catch (Exception e) {
        }
    }//GEN-LAST:event_logoutMenuActionPerformed

    private void O_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_BTNActionPerformed
        O_BTN.setEnabled(false);
    }//GEN-LAST:event_O_BTNActionPerformed

    private void C_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_BTNActionPerformed
        C_BTN.setEnabled(false);
    }//GEN-LAST:event_C_BTNActionPerformed

    private void B_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_btnActionPerformed
        B_btn.setEnabled(false);
    }//GEN-LAST:event_B_btnActionPerformed

    private void D_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_BTNActionPerformed
        D_BTN.setEnabled(false);
    }//GEN-LAST:event_D_BTNActionPerformed

    private void E_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_BTNActionPerformed
        E_BTN.setEnabled(false);
    }//GEN-LAST:event_E_BTNActionPerformed

    private void F_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_BTNActionPerformed
        F_BTN.setEnabled(false);
    }//GEN-LAST:event_F_BTNActionPerformed

    private void G_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_BTNActionPerformed
        G_BTN.setEnabled(false);
    }//GEN-LAST:event_G_BTNActionPerformed

    private void H_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_BTNActionPerformed
        H_BTN.setEnabled(false);
    }//GEN-LAST:event_H_BTNActionPerformed

    private void I_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_BTNActionPerformed
        I_BTN.setEnabled(false);
    }//GEN-LAST:event_I_BTNActionPerformed

    private void J_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_BTNActionPerformed
       J_BTN.setEnabled(false);
    }//GEN-LAST:event_J_BTNActionPerformed

    private void K_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K_BTNActionPerformed
        K_BTN.setEnabled(false);
    }//GEN-LAST:event_K_BTNActionPerformed

    private void L_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_BTNActionPerformed
        L_BTN.setEnabled(false);
    }//GEN-LAST:event_L_BTNActionPerformed

    private void M_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_BTNActionPerformed
        M_BTN.setEnabled(false);
    }//GEN-LAST:event_M_BTNActionPerformed

    private void N_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_BTNActionPerformed
        N_BTN.setEnabled(false);
    }//GEN-LAST:event_N_BTNActionPerformed

    private void P_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_BTNActionPerformed
        P_BTN.setEnabled(false);
    }//GEN-LAST:event_P_BTNActionPerformed

    private void Q_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q_BTNActionPerformed
        Q_BTN.setEnabled(false);
    }//GEN-LAST:event_Q_BTNActionPerformed

    private void R_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_BTNActionPerformed
        R_BTN.setEnabled(false);
    }//GEN-LAST:event_R_BTNActionPerformed

    private void S_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_BTNActionPerformed
        S_BTN.setEnabled(false);
    }//GEN-LAST:event_S_BTNActionPerformed

    private void T_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_btnActionPerformed
        T_btn.setEnabled(false);
    }//GEN-LAST:event_T_btnActionPerformed

    private void U_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_BTNActionPerformed
        U_BTN.setEnabled(false);
    }//GEN-LAST:event_U_BTNActionPerformed

    private void V_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_BTNActionPerformed
        V_BTN.setEnabled(false);
    }//GEN-LAST:event_V_BTNActionPerformed

    private void W_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W_BTNActionPerformed
        W_BTN.setEnabled(false);
    }//GEN-LAST:event_W_BTNActionPerformed

    private void X_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X_BTNActionPerformed
        X_BTN.setEnabled(false);
    }//GEN-LAST:event_X_BTNActionPerformed

    private void Y_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y_BTNActionPerformed
        Y_BTN.setEnabled(false);
    }//GEN-LAST:event_Y_BTNActionPerformed

    private void Z_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z_BTNActionPerformed
        Z_BTN.setEnabled(false);
    }//GEN-LAST:event_Z_BTNActionPerformed

    private void restart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart_btnActionPerformed
        A_btn.setEnabled(true);
        B_btn.setEnabled(true);
        C_BTN.setEnabled(true);
        D_BTN.setEnabled(true);
        E_BTN.setEnabled(true);
        F_BTN.setEnabled(true);
        G_BTN.setEnabled(true);
        H_BTN.setEnabled(true);
        I_BTN.setEnabled(true);
        J_BTN.setEnabled(true);
        K_BTN.setEnabled(true);
        L_BTN.setEnabled(true);
        M_BTN.setEnabled(true);
        N_BTN.setEnabled(true);
        O_BTN.setEnabled(true);
        P_BTN.setEnabled(true);
        Q_BTN.setEnabled(true);
        R_BTN.setEnabled(true);
        S_BTN.setEnabled(true);        
        T_btn.setEnabled(true);
        U_BTN.setEnabled(true);
        V_BTN.setEnabled(true);
        W_BTN.setEnabled(true);
        X_BTN.setEnabled(true);
        Y_BTN.setEnabled(true);
        Z_BTN.setEnabled(true);
              
        
        
    }//GEN-LAST:event_restart_btnActionPerformed

    private void A_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnActionPerformed
        A_btn.setEnabled(false);
    }//GEN-LAST:event_A_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_btn;
    private javax.swing.JToggleButton B_btn;
    private javax.swing.JToggleButton C_BTN;
    private javax.swing.JToggleButton D_BTN;
    private javax.swing.JToggleButton E_BTN;
    private javax.swing.JMenuItem Exit_menu;
    private javax.swing.JToggleButton F_BTN;
    private javax.swing.JToggleButton G_BTN;
    private javax.swing.JToggleButton H_BTN;
    private javax.swing.JToggleButton I_BTN;
    private javax.swing.JToggleButton J_BTN;
    private javax.swing.JToggleButton K_BTN;
    private javax.swing.JToggleButton L_BTN;
    private javax.swing.JMenu Logout_menu;
    private javax.swing.JToggleButton M_BTN;
    private javax.swing.JToggleButton N_BTN;
    private javax.swing.JToggleButton O_BTN;
    private javax.swing.JToggleButton P_BTN;
    private javax.swing.JToggleButton Q_BTN;
    private javax.swing.JToggleButton R_BTN;
    private javax.swing.JToggleButton S_BTN;
    private javax.swing.JToggleButton T_btn;
    private javax.swing.JToggleButton U_BTN;
    private javax.swing.JToggleButton V_BTN;
    private javax.swing.JToggleButton W_BTN;
    private javax.swing.JToggleButton X_BTN;
    private javax.swing.JToggleButton Y_BTN;
    private javax.swing.JToggleButton Z_BTN;
    private javax.swing.JMenu help_menu;
    private javax.swing.JButton hints_btn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JButton restart_btn;
    // End of variables declaration//GEN-END:variables

    private void printStackTrace() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
